version: '3.6'

services:
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  ui:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - api
  db:
    image: postgres
    ports:
      - "5432:5432"


volumes:
  uploads:
  node_modules: