# Generated by Django 2.2 on 2020-03-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='owner',
        ),
    ]
