# Generated by Django 2.2 on 2020-04-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0004_story_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='worlds.World'),
        ),
    ]
